all:
	gcc algo2.c config.c files.c viewer.c -o viewer -lglut -lGLU -lGL -lpthread -lm
	mv viewer bin/
	gcc cube.c -o cube -lglut -lGLU -lGL -lm
	mv cube bin/
	gcc ray.c -o ray -lglut -lGLU -lGL -lm
	mv ray bin/


