all:
	#gcc main.c connex.c bitmap.c generate.c -o GRray -lglut -lGLU -lGL -lm
	#gcc bmptest.c bitmap.c -o bmptest -lglut -lGLU -lGL
	#gcc tester.c connex.c -o tester -lm
	g++ MPEG.c connex.c bitmap.c generate.c -o MPEG -lglut -lGLU -lGL -lm -lavcodec -lavutil 
	#gcc rgbtest.c -o rgbtest

